services:
 facefusion-tensorrt:
  build:
   context: .
   dockerfile: Dockerfile.tensorrt
  command: [ 'python', 'facefusion.py', 'run', '--execution-providers', 'tensorrt' ]
  volumes:
  - /mnt/user/appdata/facefusion/.assets:/facefusion/.assets
  - /mnt/user/appdata/facefusion/.caches:/facefusion/.caches
  - /mnt/user/appdata/facefusion/.jobs:/facefusion/.jobs
  ports:
  - 7875:7860
  deploy:
   resources:
    reservations:
     devices:
     - driver: nvidia
       count: all
       capabilities: [ gpu, video ]
